### ISSUE TITLE
Error in connection handler

### ISSUE THREAD

**Issue by neur0mancer0** [FallDownTheSystem/ChessBotPy#7]
I get this error upon starting a match.

> Sending settings to client
Error in connection handler
Traceback (most recent call last):
  File "lib\site-packages\websockets\server.py", line 191, in handler
  File "main.py", line 402, in connection_handler
  File "lib\site-packages\chess\engine.py", line 2387, in popen_uci
  File "lib\site-packages\chess\engine.py", line 2379, in popen
  File "lib\site-packages\chess\engine.py", line 186, in run_in_background
  File "concurrent\futures\_base.py", line 439, in result
  File "concurrent\futures\_base.py", line 388, in __get_result
  File "lib\site-packages\chess\engine.py", line 165, in background
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "lib\site-packages\chess\engine.py", line 2371, in background
  File "asyncio\tasks.py", line 483, in wait_for
  File "lib\site-packages\chess\engine.py", line 1088, in initialize
  File "lib\site-packages\chess\engine.py", line 756, in communicate
chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 3221225501)

Not sure what I'm doing wrong, any help would be greatly appreciated

**Comment by FallDownTheSystem** [comment]
The engine is crashing for some reason. My best guess is that you're using a version that's not compatible with your hardware.

https://blog.abrok.eu/stockfish-dev-builds-faq/

**Comment by neur0mancer0** [comment]
Yep, this was the issue.  I was wracking my brain trying to figure out what it could have been and I know you wrote the engine may be an issue in some cases but for some reason it just didn't register that I should try something else. 

Anyway I have a 3770k so it's a fairly old processor and it doesn't have POPCNT.  This issue has been fixed. Thank you.
